### ISSUE TITLE
Get-CCPCredential-Unable to find type [X509Certificate].

### ISSUE THREAD

**Issue by GeethaSelvam** [pspete/CredentialRetriever#11]
Get-CCPCredential : Unable to find type [X509Certificate]. Make sure that the assembly that contains this type is loaded.
At line:5 char:1
+ Get-CCPCredential
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (X509Certificate:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

Facing this error while trying to run the Get-CCPCredential function.

**Powershell Version**
Name                           Value                                                                                        
----                           -----                                                                                        
PSVersion                      4.0                                                                                          
WSManStackVersion              3.0                                                                                          
SerializationVersion           1.1.0.1                                                                                      
CLRVersion                     4.0.30319.42000                                                                              
BuildVersion                   6.3.9600.19170                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}                                                                         
PSRemotingProtocolVersion      2.2 

Cyberark Version:10.10.1

**Comment by pspete** [comment]
[Similar issue reported for psPAS recently](https://github.com/pspete/psPAS/issues/253).
Use PowerShell 5.1, or a previous version of the module, like [3.2.12](https://www.powershellgallery.com/packages/CredentialRetriever/3.2.12), which does not have the certificate parameter.

A future fix for the module will be to require at least PowerShell 5.1.
