### ISSUE TITLE
Cannot process argument because the value of argument "name" is not valid

### ISSUE THREAD

**Issue by permster** [pspete/CredentialRetriever#14]
## Your Environment

* PowerShell Version:  5.1.14409.1018
* CredentialRetriever Branch & Version:  master/3.4.19
* CyberArk Version: 10.8 with PVWA's on 11.1

## Expected Behaviour

Expecting Get-AIMCredential to return the password properly without error like it normally does.

## Current Behaviour

Getting error message:
`Failed to get credentials: Cannot process argument because the value of argument "name" is not valid. Change the value of the "name" argument and run the operation again.`

## Possible Solution

The issue presents itself when the password has a comma in it.  For the moment we've modified the platforms forbidden characters to include comma.  However it would be nice if this can be handled properly so no customizations are required in the platform.

Looks like this has to do with the fact that Get-AIMCredential uses commas to separate the returned properties.

## Steps to Reproduce (for bug reports)

1. Set password in vault to include a comma.
2. Try to retrieve the password using the following:  `Get-AIMCredential -AppID $appid -Safe $safe -UserName $user -RequiredProps UserName,Address`

**Comment by permster** [comment]
This line [here](https://github.com/pspete/CredentialRetriever/blob/77ff389b08bc940c608397855351c32fc9a88d90/CredentialRetriever/Functions/Get-AIMCredential.ps1#L282).

Looks like this has more to do with wrapping the output from CLIPasswordSDK which is a comma separated string.  You can check to see if this bug occurs by checking if `$ReturnProps` count is less than the `$Results` count.  They should normally have the same count.

May be a few options here but the only thing that comes to mind is reorganize the properties so that password is always in the same position.  Best would probably be the last property returned.  Assuming password is the last property you could use the `$ReturnProps` count -1, so once you reach the appropriate property count anything after that in `$Results` is all considered part of the password.

If I have time I'll try and fork a fix.

**Comment by pspete** [comment]
Thanks for the report @permster .
Opted to use a different delimiter value instead of the default comma.
Issue fixed in the 3.5.22 release.

**Comment by permster** [comment]
Thanks for this.  I forgot you can change the delimiter.  One thing though.  This has created a new bug.  I think you want to change the below line to use -split instead of .split so it splits on the entire delimiter string.

https://github.com/pspete/CredentialRetriever/blob/b1440f6a44f906debe57410d2b23a1dff73cc0c0/CredentialRetriever/Functions/Get-AIMCredential.ps1#L283
