### ISSUE TITLE
Delimiter splitting bug

### ISSUE THREAD

**Issue by permster** [pspete/CredentialRetriever#16]
Thanks for this.  I forgot you can change the delimiter.  One thing though.  This has created a new bug.  I think you want to change the below line to use -split instead of .split so it splits on the entire delimiter string.

https://github.com/pspete/CredentialRetriever/blob/b1440f6a44f906debe57410d2b23a1dff73cc0c0/CredentialRetriever/Functions/Get-AIMCredential.ps1#L283

_Originally posted by @permster in https://github.com/pspete/CredentialRetriever/issues/14#issuecomment-614197139_

**Comment by pspete** [comment]
Any more details which can be provided?
Is the output incorrect?

**Comment by permster** [comment]
The properties in the output are not correct.  Your now using `"#_-_#"` to separate the properties but you have a .split() which splits on each character.  So your splitting the output on pound, underscore, and hyphen not the entire separator.  Makes the output all wonky if you have any one of those characters in your output like I do.  There are hyphens in the username in my case.

The only way I know to fix that is to switch to -split approach instead which uses regex to match the entire delimiter pattern.
https://thomasrayner.ca/whats-the-difference-between-split-and-split-in-powershell/

**Comment by pspete** [comment]
OK thanks - can reproduce when the username has a hyphen - will fix
