### ISSUE TITLE
Client Certificate Support

### ISSUE THREAD

**Issue by NathanielMaier** [pspete/CredentialRetriever#2]
I'm just starting to test this module. Does this allow the use of client certificate to authenticate to the CCP? If that's not currently supported, could it be added?

If you need more information or the formal issue format followed, let me know!

Thank you!

Nathaniel Maier

**Comment by pspete** [comment]
Hi Nathaniel,

Looking at the code as it is, support is not currently included.
Looking at the documentation, it _could be_ included, possibly.
I'm due to rebuild my lab over the next week - so will see if I can investigate and explore the art of the possible.

Cheers,

Pete

**Comment by NathanielMaier** [comment]
Thanks! I'm happy to test once you have something ready.

Nathaniel

**Comment by pspete** [comment]
@NathanielMaier, if you want to test, you can download the 
[issue-2 branch](https://github.com/pspete/CredentialRetriever/tree/issue-2) to try the functionality.

`Get-CCPCredential` now has a _`CertificateThumbPrint`_ parameter which enables client certificate authentication if a valid certificate is specified.

Usage: 

````powershell
Get-CCPCredential -CertificateThumbPrint $Cert -URL https://ccp -AppID YourApp -Safe YourSafe -Folder root -Object yourobject -UserName someuser -Address someaddress -PolicyID somePlatform
````

 if required, the thumbprints for your CurrentUser certificates can be found with the below:

````powershell
Get-ChildItem Cert:\CurrentUser\My
`````

**Comment by NathanielMaier** [comment]
@pspete Awesome! I'll try to test this in the next two weeks. Thanks so much for implementing this!

**Comment by NathanielMaier** [comment]
@pspete and not to get ahead of myself, but I think the regular PVWA REST API can require client certs too, if configured that way in IIS. I think (working from memory here) CyberArk has an API PDF that suggests requiring that for added security. Could similar functionality be added to psPAS? Would you like me to create an "issue" over there to discuss that?

**Comment by pspete** [comment]
No worries - I think i missed including it previously as I did not have the right certificate infrastructure available to develop against - as it happens I'm doing a lot of pki stuff at the minute, so no better time to work on it.
You are right, IIS for PVWA could be configured to require certificates. While pki is not an option for authenticating to the API, maybe it should be an available option in psPAS to allow for this particular configuration... [log an issue / feature request on psPAS](https://github.com/pspete/psPAS/issues/new) - I've been meaning to revisit the authentication functions for that module....

**Comment by NathanielMaier** [comment]
@pspete - I successfully tested this and it works as expected. Would you like any other information before merging this to master?

Thanks again for implementing this!

**Comment by pspete** [comment]
Nice - I'll get it merged/published. 

I may also include an update to "UseBasicParsing" as per your psPAS submission (https://github.com/pspete/psPAS/issues/117) to preempt the same issue.

**Comment by NathanielMaier** [comment]
That sounds great!

One other question... I was reviewing `Get-Help Get-CCPCredential -Full` since I haven't used this module/commandlet much yet. The PARAMETERS section confused me a bit because several parameters are listed as requred when they don't seem to be (many of the examples don't include all of those required parameters, such as `-Credential` or `-UseDefaultCredentials` or even this new `-CertificateThumbPrint` parameter. Am I just misunderstanding what "required" means?

**Comment by pspete** [comment]
The reason for this id that PowerShell ParameterSets are used to segregate mutually exclusive parameters (e.g. `-Credential` cannot be specified at the same time as `-UseDefaultCredentials`).

The `SYNTAX` section of the full help output should show you the required combinations of mandatory parameters depending on your mode of operation.

**Comment by NathanielMaier** [comment]
Ahh okay, makes sense! :)
