### ISSUE TITLE
Unexpected error behaviour saving Get-CCPCredential output to variable called $result

### ISSUE THREAD

**Issue by stukey** [pspete/CredentialRetriever#22]
If you store the output of Get-CCPCredential cmdlet in a variable named “$result” and then run the cmdlet again, storing the output in the same variable name “$result” AND an error occurs during the second or subsequent calls, the cmdlet fails with multiple errors related to adding the ‘ToSecureString’ and ‘ToCredential’ member to the output variable.

I think this is because the cmdlet function uses “$result” variable internally, and because “$result” already exists from the first successful run, it attempts to add the ‘ToSecureString’ and ‘ToCredential’ members to the “$result” variable, leading to the errors.

I think this could be fixed by changing the scope of the “$result” variable within the Get-CCPCredential function and/or adding -Force to the Add-Member cmdlets within the function.
 
Example:
 
# Run Get-CCPCredential cmdlet using a valid CCP Hostname
$result = Get-CCPCredential -AppID $appID -Safe $safe -Object $accountObject -URL "https://validccphost.com" -Certificate $myCert
 
$result
 
Content                   : Password goes here
PolicyID                  : 123345
Name                      : Test
LastTask                  : ChangeTask
UserName                  : TestAccount
CPMStatus                 : success
LastSuccessReconciliation : 1523030296
Safe                      : Test
Address                   : Test
LastSuccessVerification   : 123353454
Folder                    : Test
DeviceType                : Test
RetriesCount              : -1
LastSuccessChange         : 1234566
CreationMethod            : XYZ1
PasswordChangeInProcess   : False
 
# Run Get-CCPCredential cmdlet again, this time forcing an error by using an invalid CCP Hostname
$result = Get-CCPCredential -AppID $appID -Safe $safe -Object $accountObject -URL "https://invalidccphost.com" -Certificate $myCert
 
Add-Member : Cannot add a member with the name "ToSecureString" because a member with that name already exists. To overwrite the member anyway, add the Force parameter to
your command.
 
At line:622 char:15
+ ...   $result | Add-Member -MemberType ScriptMethod -Name ToSecureString  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (@{Content=PasswordG...nProcess=False}:PSObject) [Add-Member], InvalidOperationException
    + FullyQualifiedErrorId : MemberAlreadyExists,Microsoft.PowerShell.Commands.AddMemberCommand
 
Add-Member : Cannot add a member with the name "ToCredential" because a member with that name already exists. To overwrite the member anyway, add the Force parameter to your
command.
 
At line:629 char:15
+ ...   $result | Add-Member -MemberType ScriptMethod -Name ToCredential -V ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (@{Content=PasswordG...nProcess=False}:PSObject) [Add-Member], InvalidOperationException
    + FullyQualifiedErrorId : MemberAlreadyExists,Microsoft.PowerShell.Commands.AddMemberCommand
 
Get-CCPCredential : System.Net.WebException: The remote name could not be resolved: ' invalidccphost.com'
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
At line:1 char:11
+ $result = Get-CCPCredential -AppID $appID -Safe $safe -Object $accoun ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand,Get-CCPCredential

**Comment by pspete** [comment]
Hi @stukey - many thanks for the report, will investigate.
Suggest not using `$result` as a variable name as a short term measure until fixed :)

**Comment by stukey** [comment]
Absolutely! Easy workaround 😀

**Comment by pspete** [comment]
Thanks again for the report @stukey, now resolved in CredentialRetriever version 3.8.
