### ISSUE TITLE
Get-AIMcredential will face error if there is space in the parameter reason.

### ISSUE THREAD

**Issue by engkeen-source** [pspete/CredentialRetriever#25]

**Comment by engkeen-source** [comment]
![image](https://user-images.githubusercontent.com/71132168/146368973-d6c1b66b-bc78-4c50-9c32-53b6ee3002d5.jpeg)

**Comment by pspete** [comment]
Enable Debug to see the command string attempting to be executed (`$DebugPreference = "Continue"`).
Try including quotes in the reason string: `$Reason = '"Some Reason Here"'`

**Comment by engkeen-source** [comment]
![image](https://user-images.githubusercontent.com/71132168/146481711-04928d97-41fe-43f6-94c7-ebc6b207f28b.jpeg)

**Comment by engkeen-source** [comment]
Still cannot. Can help to fix this? 
As I need to pass variable to reason. Hence single and double quote cannot be work.

**Comment by pspete** [comment]
> Still cannot. Can help to fix this? As I need to pass variable to reason. Hence single and double quote cannot be work.

@engkeen-source - the screenshot you provide does not try to enclose the reason string in quotes as suggested.
This works:
```powershell
Get-AIMCredential -AppID SomeApp -Safe SomeSafe -Folder SomeFolder -Object SomeObject -Reason '"Some Reason"'
```

**Comment by pspete** [comment]
@engkeen-source - version 3.9 of the module contains an update which should resolve the behaviour:

```powershell
Get-AIMCredential -AppID SomeApp -Safe SomeSafe -Folder SomeFolder -Object SomeObject -Reason 'Some Reason'
```
