### ISSUE TITLE
Get-CCPCredential : The request was aborted: Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by kchass** [pspete/CredentialRetriever#30]
## Your Environment

* PowerShell Version: 5.1
* CredentialRetriever Branch & Version: 3.8.36
* CyberArk Version: 12.2

## Expected Behaviour

 Using -cert parameter works when PowerShell is running as Local Administrator, as soon as we start using it under normal user start seeing errors The request was aborted: Could not create SSL/TLS secure channel
Certificate install on server/location: Cert:\LocalMachine\my\

## Steps to Reproduce (for bug reports)

1 . Install certificate configurated on Safe  Cert:\LocalMachine\my\

2 .  Launch PowerShell as normal user:  
```powershell
$AppID = <APPID>
$Safe = <SAFENAME>
$ccpURL = <https://URL>
$cert = Get-ChildItem -LiteralPath Cert:\LocalMachine\my\<thumprint>
$result = Get-CCPCredential -AppID $AppID -Safe $Safe -UserName $apiUserName -WebServiceName AIMWebService -URL $ccpURL -Certificate $cert

New-PASSession -Credential $result.ToCredential() -BaseURI $apiURL -concurrentSession $True
```
3 . Now launch PowerShell as administrator: 
```powershell
$AppID = <APPID>
$Safe = <SAFENAME>
$ccpURL = <https://URL>
$apiUserName = <username from safe>
$cert = Get-ChildItem -LiteralPath Cert:\LocalMachine\my\<thumprint>
$result = Get-CCPCredential -AppID $AppID -Safe $Safe -UserName $apiUserName -WebServiceName AIMWebService -URL $ccpURL -Certificate $cert

New-PASSession -Credential $result.ToCredential() -BaseURI $apiURL -concurrentSession $True
```
4 .

## Sample Output

```powershell
Get-CCPCredential : The request was aborted: Could not create SSL/TLS secure channel.
At line:1 char:11
+ $result = Get-CCPCredential -AppID $AppID -Safe $Safe -UserName $apiU ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (The request was...secure channel.:ErrorRecord) [Get-CCPCredential], WebExcepti 
   on
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand,Get-CCPCr 
   edential
```

```powershell
When working successfully as administrator:
VERBOSE: received 441-byte response of content type application/json; charset=utf-8
```
## Context

Using Get-CCPCredentials to retrieval credential for service account, pass on the credentials to psPAS for New-Passession for auth and proceed with further actions depending on use case

**Comment by pspete** [comment]
Hi @kchass 
Do you see the same thing when _not_ using CredentialRetriever?

i.e.
```powershell
Invoke-RestMethod -Method GET -Uri "$ccpURL/AIMWebService/api/Accounts?AppID=$AppID&Object=PSP-AccountName&Safe=$Safe" -Certificate $cert

```

**Comment by pspete** [comment]
@kchass - you'll need to provide further details & add evidence to support the issue. 
Believe its a generic/basic misconfiguration relating to your certificates; there's no reason requiring `credentialretriever` to be run with admin privileges

**Comment by kchass** [comment]
@pspete it works with 
Invoke-RestMethod -Method GET -Uri "$ccpURL/AIMWebService/api/Accounts?AppID=$AppID&Object=PSP-AccountName&Safe=$Safe" -Certificate $cert

I'll revisit my script using the modules, something might be not right in there

![image](https://user-images.githubusercontent.com/111726107/186807304-a7483423-5a7c-4155-a413-71854ebcf035.png)

**Comment by pspete** [comment]
The only real difference between the commands is that `Get-CCPCredential` forces use of TLS 1.2:

https://github.com/pspete/CredentialRetriever/blob/9df4907ac6f91f1e2c2396dd3e0b702979aace52/CredentialRetriever/Functions/Get-CCPCredential.ps1#L721

**Comment by pspete** [comment]
> `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`
> `Invoke-RestMethod -Method GET -Uri "$ccpURL/AIMWebService/api/Accounts?AppID=$AppID&Object=PSP-AccountName&Safe=$Safe" -Certificate $cert`
@kchass - did you see if the command is still successful outside of the module when using TLS 1.2?

**Comment by kchass** [comment]
@pspete works when certificate is Cert:\CurrentUser\my 
<img width="862" alt="image" src="https://user-images.githubusercontent.com/111726107/188117192-64e6628c-e298-403a-ba5d-8e8d7cab09e4.png">


not with certificate in Cert:\LocalMachine\my\ unless run with local admin privileges


Invoke-RestMethod : The request was aborted: Could not create SSL/TLS secure channel.
At line:1 char:1
+ Invoke-RestMethod -Method GET -Uri "$ccpURL/AIMWebService/api/Account ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by pspete** [comment]
As the behaviour when using the module is identical to when not using the module, this isn't something that needs to be fixed in the CredentialRetriever module code.
Issue appears to lie somewhere in your environment.

**Comment by pspete** [comment]
Closing as no apparent issue with how the module is currently working.
Comment if you feel this is not the case :)
