### ISSUE TITLE
The underlying connection was closed: An Expected error occurred on a send

### ISSUE THREAD

**Issue by arkayali** [pspete/CredentialRetriever#31]
## Your Environment

* PowerShell Version: 5
* CredentialRetriever Branch & Version: 3.9
* CyberArk Version: 11.5 

Need to get a password from an object in CA

## Current Behaviour

![image](https://user-images.githubusercontent.com/44178884/187780650-35eb2335-fd12-4e51-b8eb-97aec54fc763.png)
![image](https://user-images.githubusercontent.com/44178884/187780750-1d19a019-6ecb-4092-8d11-f1f06a9638be.png)
![image](https://user-images.githubusercontent.com/44178884/187780768-f401609c-e13a-47cb-85ab-58eeb0c7b1d0.png)
![image](https://user-images.githubusercontent.com/44178884/187780783-55032f53-697f-43e4-9bd2-be69129cd7cc.png)
![image](https://user-images.githubusercontent.com/44178884/187780796-cfa6388b-685a-4998-83dc-09671f076386.png)

## Steps to Reproduce (for bug reports)

Type to cmdlet as shown in the screenshots 

Debug does not return any output 
Verbose: 
VERBOSE: GET https://dccw16m0409u.apt1.xxxx.pte/AIMWebService/api/Accounts?AppID=App_license&Safe=License-Cleaning-Safe&Object=LicenseCleaner with 0-byte payload

**Comment by pspete** [comment]
Sounds TLS protocol related @arkayali (the module enforces use of TLS1.2).
Unable to replicate using the command provided and there has been no recent material change to the code itself...

**Comment by arkayali** [comment]
Thanks @pspete  for your prompt response.
