### ISSUE TITLE
With Set-PSDebug -Strict: "The variable '$IsCoreCLR' cannot be retrieved because it has not been set."

### ISSUE THREAD

**Issue by BreitShoop** [pspete/CredentialRetriever#32]
## Windows Server 2016 x64

* PowerShell Version: 5.1
* CredentialRetriever Branch & Version: master; v3.9.48
* CyberArk Version: n/a

## Expected Behaviour

`$IsCoreCLR` is only referenced one place in the script, and is not set anywhere. It should be either:
1. removed
2. replaced with logic to sense whether the script is running in PowerShell Core (assuming that's the purpose of the var), or
3. become an input param

## Current Behaviour

When dot-including this script and the wrapping PowerShell script or session is using `Set-PSDebug -Strict`, the Get-CcpCredential function throws the following exception:
`The variable '$IsCoreCLR' cannot be retrieved because it has not been set.`

## Possible Solution

See expected behaviour above.

## Steps to Reproduce (for bug reports)

1. Open new Powershell session
2. Execute `Set-PSDebug -Strict`
3. Execute `. .\Get-CcpCredential.ps1`
4. run the script `Get-CcpCredential -... <valid script args>`
5. Experience the above error.

## Sample Output

`The variable '$IsCoreCLR' cannot be retrieved because it has not been set.`

**Comment by pspete** [comment]
Hi @BreitShoop ,
Thanks for the report.
$IsCoreCLR is an automatic variable in pwsh, documented here: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_automatic_variables?view=powershell-7.2#iscoreclr

**Comment by pspete** [comment]
Looking into this further, the issue is not able to be reproduced when using the module [as documented](https://github.com/pspete/CredentialRetriever#installation) (install & import the CredentialRetriever module):

![image](https://user-images.githubusercontent.com/10600090/189959735-74623f44-c4e0-4d24-9ac4-24eb67a63e8d.png)

**Comment by BreitShoop** [comment]
You are absolutely right, thanks! Apologies for the noise.

**Comment by pspete** [comment]
No bother at all.
Making a note here to maybe replace `if($IsCoreCLR){...}` with `if($PSEdition -eq "Core"){...}` in a future release.
